<?php

require_once('pages/routes.php');

?>

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Final Project</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <!--  Bootstrap stylesheet -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body class="container">
    <?php
        // Include dynamically generated navigation and CSS styles from 'routes.php'
        echo $nav;
        
        // Display any acknowledgment message (if present) from the first index of the array generated by 'routes.php'
        echo $result[0]; 

        // Dynamically inject the form generated by 'routes.php'
        echo $result[1]; 
    ?>
</body>
</html>
